sudo: required

services:
  - docker

language: go

before_install:
  - curl -sSLo vault2env https://github.com/Luzifer/vault2env/releases/download/v0.6.1/vault2env_linux_amd64
  - chmod +x vault2env

script:
  - export PATH="$(pwd):${PATH}"
  - vault2env secret/ci/luzifer_io make ci
