---

baseurl: https://luzifer.io/
config: config.yaml
metaDataFormat: yaml
permalinks:
  page: /blog/:slug
  blog: /blog/:slug
theme: luzifer.io
title: Knuts Blog
uglyUrls: false
watch: true
blackfriday:
  fractions: false
  extensions:
    - fencedCode
    - autolink
